"""Add class_year, email, phone, abbreviation, backup_id to residents

Revision ID: 9d44b7acfeba
Revises: b1304ca1d4ce
Create Date: 2025-11-28 20:56:53.669507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d44b7acfeba'
down_revision = 'b1304ca1d4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('abbreviation', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('backup_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('backup_id')
        batch_op.drop_column('abbreviation')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('class_year')

    # ### end Alembic commands ###
