"""Add ImportTransaction model and source tracking to TimeEntry

Revision ID: f8edb2b59c6a
Revises: 9d44b7acfeba
Create Date: 2025-12-29 20:52:14.269790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8edb2b59c6a'
down_revision = '9d44b7acfeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('entries_created', sa.Integer(), nullable=True),
    sa.Column('entries_skipped', sa.Integer(), nullable=True),
    sa.Column('can_undo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_transactions_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('import_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_time_entries_import_transaction', 'import_transactions', ['import_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_time_entries_import_transaction', type_='foreignkey')
        batch_op.drop_column('import_transaction_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('import_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_import_transactions_date'))

    op.drop_table('import_transactions')
    # ### end Alembic commands ###
